version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    env_file: ./.env-wikijs
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
      SSL_ACTIVE: "true"
      LETSENCRYPT_DOMAIN: wiki.decieloytierra.es
    volumes:
      - ./.config.yml:/wiki/config.yml
    restart: unless-stopped
    ports:
      - "9007:3000"

volumes:
  db-data:
